AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Lambda Layer.
Parameters:
  LayerName:
    Type: String
    Description: Name of Layer.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
    Default: Python-Chalice-Layer
Resources:    
  MyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      Content:
        S3Bucket: aks-python-dependencies
        S3Key: python.zip
      Description: Python Layer for dependencies.
      LayerName: !Sub ${LayerName}
