AWSTemplateFormatVersion: '2010-09-09'
Description: Template for S3 Bucket Creation.
Parameters:
  BucketName:  
    Type: String
    Description: Name of the bucket. 
    AllowedPattern: ^[a-z]+$
    ConstraintDescription: Only small letters allowed.
Resources:
  UploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub com-aks-bucket-api-${BucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
  # S3BucketPolicy:
  #   Type: 'AWS::S3::BucketPolicy'
  #   Properties:
  #     Bucket: !Ref UploadBucket
  #     PolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal: '*'
  #           Action:
  #             - s3:PutObject
  #           Resource: !Sub 'arn:aws:s3:::${UploadBucket}/*'